"""
This module simulates a Lotto game by generating 6 random numbers and comparing them to a set of user-selected numbers.
It uses the `random` module to generate random numbers, and the `set` data type to store and compare the numbers.
"""

import random

MY_NUMBERS = [30, 49, 42, 47, 5, 20]


def random_six_numbers():
    """Return a set of 6 unique random numbers between 1 and 49."""
    return random.sample(range(1, 50), k=6)


def check_your_luck(my_numbers, draw_six_numbers):
    """Check if the set of 'my_numbers' matches the set of 6 numbers generated by 'draw_six_numbers'.
        Return a tuple containing the two sets of numbers and the number of attempts it took to match them.
        """
    my_numbers_set = set(my_numbers)
    counter = 0

    while True:
        draw_six_numbers_set = set(draw_six_numbers())
        counter += 1
        if my_numbers_set == draw_six_numbers_set:
            return my_numbers_set, draw_six_numbers_set, counter


if __name__ == "__main__":
    draw = check_your_luck(MY_NUMBERS, random_six_numbers)
    print(f"Your numbers: {sorted(list(draw[0]))}")
    print(f"Drawn numbers: {sorted(list(draw[1]))}")
    number_of_attempts = format(draw[2], ",").replace(",", "_")
    print(f"It took {number_of_attempts} attempts to match your numbers!")
